export const LOGIN = {
    REQUEST: 'LOGIN_REQUEST',
    SUCCESS: 'LOGIN_SUCCESS',
}

export const REGISTER = {
    REQUEST: 'REGISTER_REQUEST',
    SUCCESS: 'REGISTER_SUCCESS',
}

export const GET_TASK = {
    REQUEST: 'GET_TASK_REQUEST',
    SUCCESS: 'GET_TASK_SUCCESS'
}


export const CREATE_TASK = {
    REQUEST: 'CREATE_TASK_REQUEST',
    SUCCESS: 'CREATE_TASK_SUCCESS'
}